project_id = "odgdcofbjvvzbzrzvmcl"

# Edge Functions Configuration
[functions.generate-embeddings]
verify_jwt = false

[functions.rag-chatbot]
verify_jwt = false

[functions.track-affiliate-referral]
verify_jwt = false

[functions.personalized-recommendations]
verify_jwt = false

[functions.award-badges]
verify_jwt = true

[functions.apply-badge-discount]
verify_jwt = true

[functions.analytics-report]
verify_jwt = false