// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odgdcofbjvvzbzrzvmcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ2Rjb2ZianZ2emJ6cnp2bWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjYyMjEsImV4cCI6MjA3Mjc0MjIyMX0.ISkze3Fw8mTtvc558sq0eOscnEUoUl8Z9NETiKcaXFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});